import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from "next/head";
import Layout from '@/components/Layout';
import AssetTable from '@/components/AssetTable';
import Image from 'next/image';
import backgroundImage from '../assets/easy.jpeg';
import AssetBottom from '@/components/AssetBootom';



const Home: NextPage = () => {
  const [windowWidth, setWindowWidth] = useState<number>(0);

  useEffect(() => {
    // Add event listener to update window width
    const handleResize = () => {
      setWindowWidth(window.innerWidth);
    };
    window.addEventListener('resize', handleResize);
    handleResize(); // Initial window width

    // Clean up event listener on component unmount
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <div className="bg-[#0D192B] flex items-center justify-center p-5" style={{backgroundColor:'black'}}>
        <div className="relative w-full h-full">
          <Image
            src={backgroundImage}
            alt="Background Image"
            layout="fill"
            objectFit="cover"
            className="z-0"
          />
          <Layout >
            <div>
              <AssetTable/>
              <AssetBottom />
            </div>
          </Layout>
        </div>
      </div>
    </>
  );
};

export default Home;